app/bundles/UserBundle/Entity/Role.php
<?php

namespace Mautic\UserBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Mautic\ApiBundle\Serializer\Driver\ApiMetadataDriver;
use Mautic\CoreBundle\Doctrine\Mapping\ClassMetadataBuilder;
use Mautic\CoreBundle\Entity\CacheInvalidateInterface;
use Mautic\CoreBundle\Entity\FormEntity;
use Mautic\CoreBundle\Entity\UuidInterface;
use Mautic\CoreBundle\Entity\UuidTrait;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;

/**
 * @ApiResource(
 *   attributes={
 *     "security"="false",
 *     "normalization_context"={
 *       "groups"={
 *         "role:read"
 *        },
 *       "swagger_definition_name"="Read",
 *       "api_included"={"permissions"}
 *     },
 *     "denormalization_context"={
 *       "groups"={
 *         "role:write"
 *       },
 *       "swagger_definition_name"="Write"
 *     }
 *   }
 * )
 */
class Role extends FormEntity implements CacheInvalidateInterface, UuidInterface
{
    use UuidTrait;
    public const CACHE_NAMESPACE = 'Role';
    /**
     * @var int
     *
     * @Groups({"role:read"})
     */
    private $id;

    /**
     * @var string
     *
     * @Groups({"role:read", "role:write"})
     */
    private $name;

    /**
     * @var string|null
     *
     * @Groups({"role:read", "role:write"})
     */
    private $description;

    /**
     * @var bool
     *
     * @Groups({"role:read", "role:write"})
     */
    private $isAdmin = false;

    /**
     * @var ArrayCollection<int, Permission>
     *
     * @Groups({"role:read", "role:write"})
     */
    private $permissions;

    /**
     * @var array
     *
     * @Groups({"role:read", "role:write"})
     */
    private $rawPermissions;

    /**
     * @var ArrayCollection<int, User>
     */
    private $users;

    public function __construct()
    {
        $this->permissions = new ArrayCollection();
        $this->users       = new ArrayCollection();
    }

    public static function loadMetadata(ORM\ClassMetadata $metadata): void
    {
        $builder = new ClassMetadataBuilder($metadata);

        $builder->setTable('roles')
            ->setCustomRepositoryClass(RoleRepository::class);

        $builder->addIdColumns();

        $builder->createField('isAdmin', 'boolean')
            ->columnName('is_admin')
            ->build();

        $builder->createOneToMany('permissions', 'Permission')
            ->orphanRemoval()
            ->mappedBy('role')
            ->cascadePersist()
            ->cascadeRemove()
            ->fetchExtraLazy()
            ->build();

        $builder->createField('rawPermissions', 'array')
            ->columnName('readable_permissions')
            ->build();

        $builder->createOneToMany('users', 'User')
            ->mappedBy('role')
            ->fetchExtraLazy()
            ->build();

        static::addUuidField($builder);
    }

    public static function loadValidatorMetadata(ClassMetadata $metadata): void
    {
        $metadata->addPropertyConstraint('name', new Assert\NotBlank(
            ['message' => 'mautic.core.name.required']
        ));
    }

    /**
     * Prepares the metadata for API usage.
     */
    public static function loadApiMetadata(ApiMetadataDriver $metadata): void
    {
        $metadata->setGroupPrefix('role')
            ->addListProperties(
                [
                    'id',
                    'name',
                    'description',
                    'isAdmin',
                    'rawPermissions',
                ]
            )
            ->build();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name.
     *
     * @param string $name
     *
     * @return Role
     */
    public function setName($name)
    {
        $this->isChanged('name', $name);
        $this->name = $name;

        return $this;
    }

    /**
     * Get name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Add permissions.
     *
     * @return Role
     */
    public function addPermission(Permission $permissions)
    {
        $permissions->setRole($this);

        $this->permissions[] = $permissions;

        return $this;
    }

    /**
     * Remove permissions.
     */
    public function removePermission(Permission $permissions): void
    {
        $this->permissions->removeElement($permissions);
    }

    /**
     * Get permissions.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPermissions()
    {
        return $this->permissions;
    }

    /**
     * Set description.
     *
     * @param string $description
     *
     * @return Role
     */
    public function setDescription($description)
    {
        $this->isChanged('description', $description);
        $this->description = $description;

        return $this;
    }

    /**
     * Get description.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set isAdmin.
     *
     * @param bool $isAdmin
     *
     * @return Role
     */
    public function setIsAdmin($isAdmin)
    {
        $this->isChanged('isAdmin', $isAdmin);
        $this->isAdmin = $isAdmin;

        return $this;
    }

    /**
     * Get isAdmin.
     *
     * @return bool
     */
    public function getIsAdmin()
    {
        return $this->isAdmin;
    }

    /**
     * Get isAdmin.
     *
     * @return bool
     */
    public function isAdmin()
    {
        return $this->getIsAdmin();
    }

    /**
     * Simply used to store a readable format of permissions for the changelog.
     */
    public function setRawPermissions(array $permissions): void
    {
        $this->isChanged('rawPermissions', $permissions);
        $this->rawPermissions = $permissions;
    }

    /**
     * Get rawPermissions.
     *
     * @return array
     */
    public function getRawPermissions()
    {
        return $this->rawPermissions;
    }

    /**
     * Add users.
     *
     * @return Role
     */
    public function addUser(User $users)
    {
        $this->users[] = $users;

        return $this;
    }

    /**
     * Remove users.
     */
    public function removeUser(User $users): void
    {
        $this->users->removeElement($users);
    }

    /**
     * Get users.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUsers()
    {
        return $this->users;
    }

    public function getCacheNamespacesToDelete(): array
    {
        return [
            self::CACHE_NAMESPACE,
            User::CACHE_NAMESPACE,
        ];
    }
}

app/bundles/UserBundle/Controller/UserController.php
<?php

namespace Mautic\UserBundle\Controller;

use JMS\Serializer\SerializerInterface;
use Mautic\CoreBundle\Controller\FormController;
use Mautic\CoreBundle\Factory\PageHelperFactoryInterface;
use Mautic\CoreBundle\Helper\InputHelper;
use Mautic\CoreBundle\Helper\IpLookupHelper;
use Mautic\CoreBundle\Helper\LanguageHelper;
use Mautic\CoreBundle\Model\AuditLogModel;
use Mautic\CoreBundle\Model\FormModel;
use Mautic\EmailBundle\Helper\MailHelper;
use Mautic\UserBundle\Form\Type\ContactType;
use Mautic\UserBundle\Model\RoleModel;
use Mautic\UserBundle\Model\UserModel;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class UserController extends FormController
{
    /**
     * Generate's default user list.
     *
     * @param int $page
     *
     * @return \Symfony\Component\HttpFoundation\JsonResponse|Response
     */
    public function indexAction(Request $request, PageHelperFactoryInterface $pageHelperFactory, $page = 1)
    {
        if (!$this->security->isGranted('user:users:view')) {
            return $this->accessDenied();
        }
        $pageHelper = $pageHelperFactory->make('mautic.user', $page);

        $this->setListFilters();

        $currentUserId = $this->user->getId();
        $limit         = $pageHelper->getLimit();
        $start         = $pageHelper->getStart();
        $orderBy       = $request->getSession()->get('mautic.user.orderby', 'u.lastName, u.firstName, u.username');
        $orderByDir    = $request->getSession()->get('mautic.user.orderbydir', 'ASC');
        $search        = $request->get('search', $request->getSession()->get('mautic.user.filter', ''));
        $search        = html_entity_decode($search);
        $request->getSession()->set('mautic.user.filter', $search);

        // do some default filtering
        $filter = ['string' => $search, 'force' => ''];
        $tmpl   = $request->isXmlHttpRequest() ? $request->get('tmpl', 'index') : 'index';
        $users  = $this->getModel('user.user')->getEntities(
            [
                'start'      => $start,
                'limit'      => $limit,
                'filter'     => $filter,
                'orderBy'    => $orderBy,
                'orderByDir' => $orderByDir,
            ]);

        // Check to see if the number of pages match the number of users
        $count = count($users);
        if ($count && $count < ($start + 1)) {
            // the number of entities are now less then the current page so redirect to the last page
            $lastPage = $pageHelper->countPage($count);
            $pageHelper->rememberPage($lastPage);
            $returnUrl = $this->generateUrl('mautic_user_index', ['page' => $lastPage]);

            return $this->postActionRedirect([
                'returnUrl'      => $returnUrl,
                'viewParameters' => [
                    'page' => $lastPage,
                    'tmpl' => $tmpl,
                ],
                'contentTemplate' => 'Mautic\UserBundle\Controller\UserController::indexAction',
                'passthroughVars' => [
                    'activeLink'    => '#mautic_user_index',
                    'mauticContent' => 'user',
                ],
            ]);
        }

        $pageHelper->rememberPage($page);

        return $this->delegateView([
            'viewParameters'  => [
                'items'         => $users,
                'searchValue'   => $search,
                'page'          => $page,
                'limit'         => $limit,
                'tmpl'          => $tmpl,
                'currentUserId' => $currentUserId,
                'permissions'   => [
                    'create' => $this->security->isGranted('user:users:create'),
                    'edit'   => $this->security->isGranted('user:users:editother'),
                    'delete' => $this->security->isGranted('user:users:deleteother'),
                ],
            ],
            'contentTemplate' => '@MauticUser/User/list.html.twig',
            'passthroughVars' => [
                'route'         => $this->generateUrl('mautic_user_index', ['page' => $page]),
                'mauticContent' => 'user',
            ],
        ]);
    }

    /**
     * Generate's form and processes new post data.
     *
     * @return \Symfony\Component\HttpFoundation\JsonResponse|Response
     */
    public function newAction(Request $request, LanguageHelper $languageHelper, UserPasswordHasherInterface $hasher)
    {
        if (!$this->security->isGranted('user:users:create')) {
            return $this->accessDenied();
        }

        /** @var UserModel $model */
        $model = $this->getModel('user.user');

        // retrieve the user entity
        $user = $model->getEntity();

        // set the return URL for post actions
        $returnUrl = $this->generateUrl('mautic_user_index');

        // set the page we came from
        $page = $request->getSession()->get('mautic.user.page', 1);

        // get the user form factory
        $action = $this->generateUrl('mautic_user_action', ['objectAction' => 'new']);
        $form   = $model->createForm($user, $this->formFactory, $action);

        // Check for a submitted form and process it
        if ('POST' === $request->getMethod()) {
            $valid = false;
            if (!$cancelled = $this->isFormCancelled($form)) {
                // check to see if the password needs to be rehashed
                $formUser          = $request->request->all()['user'] ?? [];
                $submittedPassword = $formUser['plainPassword']['password'] ?? null;
                $password          = $model->checkNewPassword($user, $hasher, $submittedPassword);

                if ($valid = $this->isFormValid($form)) {
                    // form is valid so process the data
                    $user->setPassword($password);
                    $model->saveEntity($user);

                    // check if the user's locale has been downloaded already, fetch it if not
                    $installedLanguages = $languageHelper->getSupportedLanguages();

                    if ($user->getLocale() && !array_key_exists($user->getLocale(), $installedLanguages)) {
                        $fetchLanguage = $languageHelper->extractLanguagePackage($user->getLocale());

                        // If there is an error, we need to reset the user's locale to the default
                        if ($fetchLanguage['error']) {
                            $user->setLocale(null);
                            $model->saveEntity($user);
                            $message     = 'mautic.core.could.not.set.language';
                            $messageVars = [];

                            if (isset($fetchLanguage['message'])) {
                                $message = $fetchLanguage['message'];
                            }

                            if (isset($fetchLanguage['vars'])) {
                                $messageVars = $fetchLanguage['vars'];
                            }

                            $this->addFlashMessage($message, $messageVars);
                        }
                    }

                    $this->addFlashMessage('mautic.core.notice.created', [
                        '%name%'      => $user->getName(),
                        '%menu_link%' => 'mautic_user_index',
                        '%url%'       => $this->generateUrl('mautic_user_action', [
                            'objectAction' => 'edit',
                            'objectId'     => $user->getId(),
                        ]),
                    ]);
                }
            }

            if ($cancelled || ($valid && $this->getFormButton($form, ['buttons', 'save'])->isClicked())) {
                return $this->postActionRedirect([
                    'returnUrl'       => $returnUrl,
                    'viewParameters'  => ['page' => $page],
                    'contentTemplate' => 'Mautic\UserBundle\Controller\UserController::indexAction',
                    'passthroughVars' => [
                        'activeLink'    => '#mautic_user_index',
                        'mauticContent' => 'user',
                    ],
                ]);
            } elseif ($valid && !$cancelled) {
                return $this->editAction($request, $languageHelper, $hasher, $user->getId(), true);
            }
        }

        return $this->delegateView([
            'viewParameters'  => ['form' => $form->createView()],
            'contentTemplate' => '@MauticUser/User/form.html.twig',
            'passthroughVars' => [
                'activeLink'    => '#mautic_user_new',
                'route'         => $action,
                'mauticContent' => 'user',
            ],
        ]);
    }

    /**
     * Generates edit form and processes post data.
     *
     * @param int  $objectId
     * @param bool $ignorePost
     *
     * @return \Symfony\Component\HttpFoundation\JsonResponse|Response
     */
    public function editAction(Request $request, LanguageHelper $languageHelper, UserPasswordHasherInterface $hasher, $objectId, $ignorePost = false)
    {
        if (!$this->security->isGranted('user:users:edit')) {
            return $this->accessDenied();
        }
        $model = $this->getModel('user.user');
        \assert($model instanceof UserModel);
        $user = $model->getEntity($objectId);
        if (null === $user) {
            return $this->postActionRedirect([
                'returnUrl'       => $this->generateUrl('mautic_user_index'),
                'flashes'         => [
                    [
                        'type'    => 'error',
                        'msg'     => 'mautic.user.user.error.notfound',
                        'msgVars' => ['%id%' => $objectId],
                    ],
                ],
            ]);
        }
        $oldEmail = $user->getEmail();

app/bundles/UserBundle/Resources/views/User/contact.html.twig
{% extends '@MauticCore/Default/content.html.twig' %}
{% block mauticContent %}user{% endblock %}
{% block headerTitle %}{{ 'mautic.user.user.header.contact'|trans({'%name%': user.getName()}) }}{% endblock %}

{% block content %}
<div class="panel">
    <div class="panel-body pa-md">
        {{ form(form) }}
    </div>
</div>
{% endblock %}

app/bundles/UserBundle/Resources/views/User/form.html.twig
{% extends '@MauticCore/Default/content.html.twig' %}
{% block mauticContent %}user
{% endblock %}
{% set userId = form.vars.data.getId() %}
{% if userId is not empty %}
	{% set user = form.vars.data.getName() %}
	{% set header = 'mautic.user.user.header.edit'|trans({'%name%': user}) %}
{% else %}
	{% set header = 'mautic.user.user.header.new'|trans %}
{% endif %}

{% block headerTitle %}
	{{ header }}
{% endblock %}


{% block content %}

	<!-- start: box layout -->
	<div
		class="box-layout">
		<!-- container -->
		{{ form_start(form) }}
		<div class="col-md-9 height-auto bdr-r">
			<div class="pa-md">
				<div class="form-group mb-0">
					<div class="row">
						<div class="col-sm-6{{ form.firstName.vars.errors|length ? ' has-error' : '' }}">
							<h3 class="mb-lg mt-lg">{{ 'mautic.user.config.title.personal_information'|trans }}</h3>
							<div class="form-group">
								<label class="control-label mb-xs">{{ form_label(form.firstName) }}</label>
								{{ form_widget(form.firstName, {'attr' : {'placeholder' : form.firstName.vars.label }}) }}
								{{ form_errors(form.firstName) }}
							</div>
							<div class="form-group{{ form.lastName.vars.errors|length ? ' has-error' : '' }}">
								<label class="control-label mb-xs">{{ form_label(form.lastName) }}</label>
								{{ form_widget(form.lastName, {'attr' : {'placeholder' : form.lastName.vars.label }}) }}
								{{ form_errors(form.lastName) }}
							</div>
							<div class="form-group{{ form.role.vars.errors|length ? ' has-error' : '' }}">
								<label class="control-label mb-xs">{{ form_label(form.role) }}</label>
								{{ form_widget(form.role, {'attr' : {'placeholder' : form.role.vars.label }}) }}
								{{ form_errors(form.role) }}
							</div>
							<div class="form-group pb-lg{{ form.position.vars.errors|length ? ' has-error' : '' }}">
								<label class="control-label mb-xs">{{ form_label(form.position) }}</label>
								{{ form_widget(form.position, {'attr' : {'placeholder' : form.position.vars.label }}) }}
								{{ form_errors(form.position) }}
							</div>
							<div class="form-group pt-md{{ form.signature.vars.errors|length ? ' has-error' : '' }}">
								<label class="control-label mb-xs">{{ form_label(form.signature) }}</label>
								{{ form_widget(form.signature, {'attr' : {'placeholder' : form.signature.vars.label }}) }}
								{{ form_errors(form.signature) }}
								<p class="help-text">{{ 'mautic.user.config.signature.admin.helper'|trans }} </p>
							</div>
						</div>
						<div class="col-sm-6">
							<h3 class="mb-lg mt-lg">{{ 'mautic.user.config.title.account_data_security'|trans }}</h3>
							<div class="form-group{{ form.username.vars.errors|length ? ' has-error' : '' }}">
									{{ form_label(form.username) }}
									{{ form_widget(form.username, {'attr' : {'placeholder' : form.username.vars.label }}) }}
									{{ form_errors(form.username) }}
							</div>
							<div class="form-group{{ form.email.vars.errors|length ? ' has-error' : '' }}">
								{{ form_label(form.email) }}
								{{ form_widget(form.email, {'attr' : {'placeholder' : form.email.vars.label }}) }}
								{{ form_errors(form.email) }}
							</div>
							{{ form_widget(form.plainPassword, {'attr' : {'placeholder' : form.plainPassword.vars.label }}) }}
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-3 height-auto">
			<div class="pr-lg pl-lg pt-md pb-md">
				<h3 class="mb-lg mt-lg">{{ 'mautic.user.config.title.locale'|trans }}</h3>
				{{ form_rest(form) }}
			</div>
		</div>
		{% if editAction is defined and editAction == true %}
			{{- include('@MauticUser/User/recent_activity.html.twig', {
        'logs'  : logs,
        'users' : users,
        'roles' : roles,
    	}) -}}
		{% endif %}

		{{ form_end(form) }}
	</div>

{% endblock %}

app/bundles/UserBundle/Resources/views/User/list.html.twig
{% set isIndex = tmpl == 'index' ? true : false %}
{% set tmpl = 'list' %}

{% extends isIndex ? '@MauticCore/Default/content.html.twig' : '@MauticCore/Default/raw_output.html.twig' %}
{% block mauticContent %}user
{% endblock %}
{% block headerTitle %}
	{% trans %}mautic.user.users{% endtrans %}
{% endblock %}

{% block content %}
	{% if isIndex %}
	<div id="page-list-wrapper" class="panel panel-default">
		{{- include('@MauticCore/Helper/list_toolbar.html.twig', {
			'searchValue': searchValue,
			'action': currentRoute,
			'page_actions': {
				'templateButtons': {
					'new': permissions['create'],
				},
				'routeBase': 'user',
				'langVar': 'user.user',
			},
			'bulk_actions': {
				'routeBase': 'user',
				'langVar': 'user.user',
				'templateButtons': {
					'delete': permissions['delete']
				}
			},
			'quickFilters': [
				{
					'search': 'mautic.user.user.searchcommand.isadmin',
					'label': 'mautic.user.role.form.isadmin',
					'tooltip': 'mautic.core.search.quickfilter.is_admin',
					'icon': 'ri-admin-line'
				},
				{
					'search': 'mautic.core.searchcommand.ispublished',
					'label': 'mautic.core.form.active',
					'tooltip': 'mautic.core.search.quickfilter.is_published',
					'icon': 'ri-check-line'
				},
				{
					'search': 'mautic.core.searchcommand.isunpublished',
					'label': 'mautic.core.form.inactive',
					'tooltip': 'mautic.core.search.quickfilter.is_unpublished',
					'icon': 'ri-close-line'
				}
			]
		}) -}}
		<div class="page-list">
			{{ block('listResults') }}
		</div>
	</div>
	{% else %}
		{{ block('listResults') }}
	{% endif %}
{% endblock %}

{% block listResults %}
	<div class="table-responsive">
		<table class="table table-hover user-list" id="userTable">
			<thead>
				<tr>
					{{- include('@MauticCore/Helper/tableheader.html.twig', {
                    'checkall'        : 'true',
                    'target'          : '#userTable'
            }) -}}

					<th class="visible-md visible-lg col-user-avatar"></th>
					{{- include('@MauticCore/Helper/tableheader.html.twig', {
                    'sessionVar' : 'user',
                    'orderBy'    : 'u.lastName, u.firstName, u.username',
                    'text'       : 'mautic.core.name',
                    'class'      : 'col-user-name',
                    'default'    : true,
                }) -}}
					{{- include('@MauticCore/Helper/tableheader.html.twig', {
                    'sessionVar' : 'user',
                    'orderBy'    : 'u.username',
                    'text'       : 'mautic.core.username',
                    'class'      : 'col-user-username',
                }) -}}
					{{- include('@MauticCore/Helper/tableheader.html.twig', {
                    'sessionVar' : 'user',
                    'orderBy'    : 'u.email',
                    'text'       : 'mautic.core.type.email',
                    'class'      : 'visible-md visible-lg col-user-email',
                }) -}}

					{{- include('@MauticCore/Helper/tableheader.html.twig', {
                    'sessionVar' : 'user',
                    'orderBy'    : 'r.name',
                    'text'       : 'mautic.user.role',
                    'class'      : 'visible-md visible-lg col-user-role',
                }) -}}

					{{- include('@MauticCore/Helper/tableheader.html.twig', {
                    'sessionVar' : 'user',
                    'orderBy'    : 'u.lastLogin',
                    'text'       : 'mautic.user.lastlogin',
                    'class'      : 'visible-md visible-lg col-user-lastlogin',
                }) -}}

					{{- include('@MauticCore/Helper/tableheader.html.twig', {
                    'sessionVar' : 'user',
                    'orderBy'    : 'u.id',
                    'text'       : 'mautic.core.id',
                    'class'      : 'visible-md visible-lg col-user-id',
                }) -}}

				</tr>
			</thead>
			<tbody>
				{% for item in items %}
					<tr>
						<td>
							{{- include('@MauticCore/Helper/list_actions.html.twig', {
                            'item'            : item,
                            'templateButtons' : {
                                'edit'   : permissions['edit'],
                                'delete' : permissions['delete'],
                            },
                            'routeBase' : 'user',
                            'langVar'   : 'user.user',
                            'pull'      : 'left',
                   }) -}}
						</td>
						<td class="visible-md visible-lg">
							<img class="img img-responsive img-thumbnail w-44" src="{{ gravatarGetImage(item.getEmail(), '50') }}"/>
						</td>
						<td>
							<div>
								{% if item.getId() != currentUserId %}
									{{- include('@MauticCore/Helper/publishstatus_icon.html.twig', {
										'item'  : item,
										'model' : 'user',
									}) -}}
								{% endif %}
								{% if permissions['edit'] %}
									<a href="{{ path( 'mautic_user_action', {'objectAction' : 'edit', 'objectId' : item.getId()} ) }}" data-toggle="ajax">
										{{ item.getName(true) }}
									</a>
								{% else %}
									{{ item.getName(true) }}
								{% endif %}
							</div>
							<div class="small">
								<em>{{ item.getPosition() }}</em>
							</div>
						</td>
						<td>{{ item.getUsername() }}</td>
						<td class="visible-md visible-lg">
							<a href="mailto: {{ item.getEmail() }}">{{ item.getEmail() }}</a>
						</td>
						<td class="visible-md visible-lg">{{ item.getRole().getName() }}</td>
						<td class="visible-md visible-lg">{{ dateToText(item.getLastLogin(), 'local', 'Y-m-d H:i:s', true) }}</td>
						<td class="visible-md visible-lg">{{ item.getId() }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<div class="panel-footer">
			{{- include('@MauticCore/Helper/pagination.html.twig', {
            'totalItems' : items|length,
            'page'       : page,
            'limit'      : limit,
            'baseUrl'    : path('mautic_user_index'),
            'sessionVar' : 'user',
       }) -}}
		</div>
	</div>
{% endblock %}